services:
  - type: web
    name: qrug-pic50-predictor
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y default-jre
      pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
